spring:
  application:
    name: gateway-service

server:
  #  port: 8443
  #  ssl:
  #    key-store: classpath:keystore/keystore.p12
  #    key-store-password: tkpassword
  #    key-store-type: pkcs12
  #    key-alias: tktawfik
  #    key-password: tkpassword
  port: 8080
#  error:
#    include-stacktrace: always
#    include-exception: true
#    include-message: always


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

#security:
#  require-ssl: true
#
#trust:
#  store: classpath:/keystore.p12
#   password: tkpassword

zuul:
  ignored-services: '*'
  routes:
    integration-service:
      path: /is/**
      service-id: integration-service
#    auth-service:
#      path: /auth/**
#      service-id: auth-service
#      strip-prefix: false
#      sensitive-headers: Cookie,Set-Cookie

integration-service:
  ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 600000
